using System.Text;

namespace MinimalSerializers.Json.Discovery;

/// <summary>
/// Emits a partial JsonSerializerContext with [JsonSerializable] attributes.
/// </summary>
public static class MinimalJsonContextSourceEmitter
{
    public static string Emit(DiscoveredContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine(
            "#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member"
        );
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(context.NamespaceName))
        {
            sb.Append("namespace ").Append(context.NamespaceName).AppendLine(";");
            sb.AppendLine();
        }

        foreach (var root in context.Roots)
        {
            sb.Append("[JsonSerializable(typeof(").Append(root.TypeDisplayName).Append(')');
            if (!string.IsNullOrEmpty(root.TypeInfoPropertyName))
            {
                sb.Append(", TypeInfoPropertyName = \"")
                    .Append(root.TypeInfoPropertyName)
                    .Append('"');
            }

            sb.AppendLine(")]");
        }

        sb.Append(context.Accessibility)
            .Append(" partial class ")
            .Append(context.TypeName)
            .AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GetGeneratedFileName(DiscoveredContext context)
    {
        var ns = string.IsNullOrEmpty(context.NamespaceName)
            ? "Global"
            : context.NamespaceName.Replace('.', '_');
        return $"{ns}.{context.TypeName}.MinimalJson.g.cs";
    }
}
