<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Sample.Host</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sample.Contracts\Sample.Contracts.csproj" />
    <ProjectReference Include="..\..\src\MinimalSerializers.Json\MinimalSerializers.Json.csproj" />
  </ItemGroup>
</Project>
